In [1]:
import numpy as np

In [2]:
print(np.__version__)

2.1.3


In [5]:
vector = np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [6]:
vector = np.arange(10,50)
print(vector[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [24]:
massive = np.random.random((5,5))
massive_median = np.median(massive, axis=1)
massive_average = np.average(massive, axis=1)
print(massive, massive_median, massive_average,sep="\n")

[[0.47420116 0.42607463 0.82926768 0.33327572 0.32408225]
 [0.82875299 0.0382329  0.43907182 0.61243175 0.78553746]
 [0.61409832 0.68707029 0.79551117 0.95132456 0.52599468]
 [0.70360947 0.4348838  0.15544479 0.38757123 0.90395064]
 [0.86950397 0.91200656 0.86680094 0.61091478 0.16217987]]
[0.42607463 0.61243175 0.68707029 0.4348838  0.86680094]
[0.47738029 0.54080538 0.7147998  0.51709199 0.68428122]


In [27]:
massive = np.array([x for x in range(27)])
matrix = massive.reshape(3,3,3)
print(massive, matrix, sep="\n")

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [38]:
massive = np.array([[3.5,1.9,8.45], [4.7, 7.9, 1.9]])
print(massive.astype(int))

[[3 1 8]
 [4 7 1]]


In [45]:
massive = np.array([[1, 0, 0], [1, 1, 1],  [0, 0, 1]])
print(massive.astype(bool))

[[ True False False]
 [ True  True  True]
 [False False  True]]


In [127]:
massive1 = np.array([[1,2,3], [4,5,6]])
massive2 = np.array([[7,8,9], [10,11,12]])
mass= np.hstack((massive1, massive2))
print(mass)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [128]:
massive1 = np.array([[1,2],
 [3,4],
 [5,6]])
massive2 = np.array([[7,8],
 [9,10],
 [10,11]])
mass = np.vstack((massive1, massive2))
print(mass)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [10 11]]


In [132]:
a = np.array([1,2,3,4,5])
b = np.array([1,3,2,4,5])
mass = np.where((a == b))
print(mass)

(array([0, 3, 4]),)


In [138]:
a = np.array([[1,2,3], 
 [4,5,6], 
 [7,8,9]])
b = np.array([[2,3,4], 
 [5,6,7], 
 [8,9,10]])
ab = np.dot(a,b)
ba = np.dot(b,a)
print(ab, ba, sep="\n")

[[ 36  42  48]
 [ 81  96 111]
 [126 150 174]]
[[ 42  51  60]
 [ 78  96 114]
 [114 141 168]]


In [144]:
a = np.array([[1,2,3], 
 [4,5,6], 
 [7,8,9]])
trans = np.transpose(a)
print(trans)
print(a)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [146]:
angles = np.array([3.14, 3.14/2, 6.28])
sin = np.sin(angles)
print(sin)

[ 0.00159265  0.99999968 -0.0031853 ]


In [148]:
v = np.random.random(size=[10])
sort = np.sort(v)
print(v)
print(sort)

[0.87376449 0.53843417 0.42162051 0.87544568 0.56023778 0.59148665
 0.01051327 0.39021668 0.86448854 0.27953029]
[0.01051327 0.27953029 0.39021668 0.42162051 0.53843417 0.56023778
 0.59148665 0.86448854 0.87376449 0.87544568]


In [150]:
a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,5])
draw = np.array_equal(a,b)
print(draw)

True


In [161]:
Z = np.random.random(10)
np.sort(Z)
Z[9] = 0
print(Z)

[0.18825105 0.8786766  0.44488034 0.10516754 0.97762172 0.31685513
 0.63902275 0.29838608 0.08564926 0.        ]
